# Generated by Django 5.2.13 on 2026-04-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projectimage_discarded_for_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='imagegroup',
            index=models.Index(fields=['project', 'deleted_at'], name='core_imageg_project_947a6a_idx'),
        ),
    ]
