# Generated by Django 5.2.6 on 2026-04-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dataset_version_export_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegroup',
            name='detection_filter',
            field=models.CharField(blank=True, default='', help_text='Active detection filter name (empty = none).', max_length=64),
        ),
        migrations.AddField(
            model_name='imagegroup',
            name='detection_filter_params',
            field=models.JSONField(blank=True, default=dict, help_text='Parameters for the selected detection filter (schema varies per filter).'),
        ),
    ]
